
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8181/realms/Alliance
            jwk-set-uri: http://localhost:8181/realms/Alliance/protocol/openid-connect/certs

server:
  port: 4041
