
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8181/realms/Alliance
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 4041

jwt:
  auth:
    converter:
      resource-id: "spring-rest-api"
      principle-attribute: "preferred_username"
